[project]
name = "mcp-uk-open-data"
version = "0.1.0"
description = "Dockerized MCP server exposing UK open data tools (ONS, data.gov.uk)"
requires-python = ">=3.11"
dependencies = ["mcp>=1.0.0","pydantic>=2.8","requests>=2.32.0"]
